### ISSUE TITLE
And how to make the user authorized after he passes authentication through ADFS?

### ISSUE THREAD

**Issue by lexuschert** [Codinlab/AdfsOAuth#2]
Hi!
And how to make the user authorized after he passes authentication through ADFS? You can give an example of the example project .NET Core MVC?

I'm trying to use your solution, but the user is not authorized.
Result on the page where the redirect occurs:
IsAuthenticated: False
Claims.Count: 0

`IsAuthenticated: @User.Identity.IsAuthenticated`
`Claims.Count: @User.Claims.Count()`

PS. I want to create on the basis of the received data from ADFS in the user database

**Comment by TFleury** [comment]
You probably forgot to add `AutomaticAuthenticate = true` in `AdfsOAuthOptions` options.
I will add it to the sample code.

Let me know if it solved you issue.

**Comment by lexuschert** [comment]
I did, but it did not help. Maybe I missed something else.
After the redirect, the cookie value is N
Example Cookies:
`Name: .AspNetCore.Correlation.Adfs.sCY2F8qDuvUn6F4u_Il2ru8rxEatUDaIWY1BGh8shiU Value: N`

I will sort this out :)

**Comment by lexuschert** [comment]
Finally done as described in the article - http://www.carbon60.com/blog/using-adfs-3-0-with-mvc-6-asp-net-5
Only there were problems with the certificate, gave out an error, that not valid keys. I turned off the validation and it all worked.
Thank you.
